services:
  goproxy:
    image: ghcr.io/woodchen-ink/goproxy:latest
    container_name: goproxy
    restart: unless-stopped
    ports:
      - "37776:7776" #http最低
      - "37777:7777" #http随机
      - "37778:7778" # Web UI 面板
      - "37779:7779" # socks5随机代理
      - "37780:7780" # socks5最低延迟代理
    environment:
      - TZ=${TZ:-Asia/Shanghai} # 容器时区设置，默认使用上海时间
      - DATA_DIR=/app/data
      - WEBUI_PASSWORD=web密码
      - BLOCKED_COUNTRIES=CN,RU,HK
      - PROXY_AUTH_ENABLED=true
      - PROXY_AUTH_USERNAME=代理用户名
      - PROXY_AUTH_PASSWORD=代理密码
      - SOCKS5_DNS_MODE=local
      - SOCKS5_ALLOW_HTTP_UPSTREAM=true
    volumes:
      - goproxy-data:/app/data # 挂载数据卷，实现数据持久化

volumes:
  goproxy-data: # 声明命名数据卷
